### ISSUE TITLE
关于api的相关问题

### ISSUE THREAD

**Issue by paul623** [flymyd/HaierAirBox#1]
目前海尔空气盒子配套的app已经基本报废
不知这个项目的目的是什么
如果能够开放其中的一些请求就会方便很多

**Comment by flymyd** [comment]
你好。之前通过挂装单片机的方式对空气盒子实现了数据劫持的操作，但过程繁琐。使用homeassistant配合空气盒子插件的方式可以对空气盒子进行操作。请移步至瀚思彼岸论坛寻找教程。

**Comment by flymyd** [comment]
[海尔空气盒子接入homeassistant](https://bbs.hassbian.com/thread-9234-1-1.html)

**Comment by paul623** [comment]
> 你好。之前通过挂装单片机的方式对空气盒子实现了数据劫持的操作，但过程繁琐。使用homeassistant配合空气盒子插件的方式可以对空气盒子进行操作。请移步至瀚思彼岸论坛寻找教程。

好的，非常感谢

**Comment by flymyd** [comment]
另：硬件部分代码repo见下
[github](https://github.com/GUGU-AirBox/GUGU_AirBox)
